name: Java Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17', '21']
    name: Java ${{ matrix.java }} Build
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk+fx
          cache: 'gradle'

      - name: <>-- Build --<>
        run: ./gradlew build createAllExecutables --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: build/launch4j
